import { config as dotenvConfig } from 'dotenv';
dotenvConfig({ path: '.env' });

const {
  JWT_SECRET: jwtSecret,
  DATABASE_HOST: databaseHost,
  DATABASE_PORT: databasePort,
  DATABASE_USERNAME: databaseUsername,
  DATABASE_PASSWORD: databasePassword,
  DB_CONNECTION: dbConnection,
  DATABASE_NAME: databaseName,
  DATABASE_SSL: databaseSsl,
  CLOUDINARY_NAME: cloudinaryName,
  CLOUDINARY_API_KEY: cloudinaryApiKey,
  CLOUDINARY_API_SECRET: cloudinaryApiSecret,
  CLOUDINARY_URL: cloudinaryUrl,
  PORT: port,
  PROJECT_ID: projectId,
  PRIVATE_KEY: privateKey,
  CLIENT_EMAIL: clientEmail,
  GOOGLE_CLIENT_ID: googleClientId,
  MAIL_USER: mailUser,
  MAIL_PASSWORD: mailPassword,
  MAIL_HOST: mailHost,
  MAIL_DISPLAY_NAME: mailDisplayName,
} = process.env;

export const configEnvs = {
  jwtSecret,
  databaseHost,
  databasePort,
  databaseUsername,
  databasePassword,
  dbConnection,
  databaseName,
  databaseSsl,
  cloudinaryName,
  cloudinaryApiKey,
  cloudinaryApiSecret,
  cloudinaryUrl,
  port,
  projectId,
  privateKey,
  clientEmail,
  googleClientId,
  mailUser,
  mailPassword,
  mailHost,
  mailDisplayName,
};
