import { MigrationInterface, QueryRunner } from "typeorm";

export class AddedInventoryTable1738538924803 implements MigrationInterface {
    name = 'AddedInventoryTable1738538924803'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP FOREIGN KEY \`FK_5c3bec1682252c36fa161587738\``);
        await queryRunner.query(`CREATE TABLE \`inventory\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantityAvailable\` int NOT NULL DEFAULT '0', \`quantityReserved\` int NOT NULL DEFAULT '0', \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`productId\` int NULL, UNIQUE INDEX \`REL_c8622e1e24c6d054d36e882449\` (\`productId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP COLUMN \`quantity\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP COLUMN \`product_id\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD \`inventoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`inventoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD UNIQUE INDEX \`IDX_dcf7550e6f03fb1414ed41628f\` (\`inventoryId\`)`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` DROP FOREIGN KEY \`FK_236a83d394e727d0b8e2a004efb\``);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` DROP FOREIGN KEY \`FK_5e8a95d64e5b56059fefa78e85e\``);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` CHANGE \`id_product\` \`id_product\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` CHANGE \`id_sell\` \`id_sell\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`clients\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`clients\` CHANGE \`phone\` \`phone\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`contactPhone\` \`contactPhone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`city\` \`city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`notes\` \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` DROP FOREIGN KEY \`FK_28c643f280d3f04dd8d53c4b906\``);
        await queryRunner.query(`ALTER TABLE \`detail_order\` DROP FOREIGN KEY \`FK_4c3eb3ee75d81ef599c73aa396b\``);
        await queryRunner.query(`ALTER TABLE \`detail_order\` CHANGE \`orderId\` \`orderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` CHANGE \`productId\` \`productId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sells\` DROP FOREIGN KEY \`FK_076b4238cf89d6b602e7a75d101\``);
        await queryRunner.query(`ALTER TABLE \`sells\` DROP FOREIGN KEY \`FK_98783c65c664df6dd903b561d5f\``);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`sellDate\` \`sellDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`clientName\` \`clientName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`id_user\` \`id_user\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`id_client\` \`id_client\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_fd5199dbe0a822181eb05795e6e\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_f6a89a945c446c9fdae718d1709\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_2fa435da96296948770716303d5\``);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`sellDate\` \`sellDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`clientName\` \`clientName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`endDate\` \`endDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`id_user\` \`id_user\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`id_client\` \`id_client\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`productId\` \`productId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP FOREIGN KEY \`FK_63cca4adcd28b6fe19bc4ceb22f\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_0633fb8c8bf00bb25890f4b2ae2\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_103cec6966ad062a779ec25536e\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_c143cbc0299e1f9220c4b5debd8\``);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`id_category\` \`id_category\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`added_by\` \`added_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`supplierId\` \`supplierId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_dcf7550e6f03fb1414ed41628f\` ON \`products\` (\`inventoryId\`)`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` ADD CONSTRAINT \`FK_236a83d394e727d0b8e2a004efb\` FOREIGN KEY (\`id_product\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` ADD CONSTRAINT \`FK_5e8a95d64e5b56059fefa78e85e\` FOREIGN KEY (\`id_sell\`) REFERENCES \`sells\`(\`idSell\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` ADD CONSTRAINT \`FK_28c643f280d3f04dd8d53c4b906\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` ADD CONSTRAINT \`FK_4c3eb3ee75d81ef599c73aa396b\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sells\` ADD CONSTRAINT \`FK_076b4238cf89d6b602e7a75d101\` FOREIGN KEY (\`id_user\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sells\` ADD CONSTRAINT \`FK_98783c65c664df6dd903b561d5f\` FOREIGN KEY (\`id_client\`) REFERENCES \`clients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_fd5199dbe0a822181eb05795e6e\` FOREIGN KEY (\`id_user\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_f6a89a945c446c9fdae718d1709\` FOREIGN KEY (\`id_client\`) REFERENCES \`clients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_2fa435da96296948770716303d5\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD CONSTRAINT \`FK_63cca4adcd28b6fe19bc4ceb22f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD CONSTRAINT \`FK_29cfdad4178e68164711ae51bd7\` FOREIGN KEY (\`inventoryId\`) REFERENCES \`inventory\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory\` ADD CONSTRAINT \`FK_c8622e1e24c6d054d36e8824490\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_0633fb8c8bf00bb25890f4b2ae2\` FOREIGN KEY (\`id_category\`) REFERENCES \`categories\`(\`idCategory\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_103cec6966ad062a779ec25536e\` FOREIGN KEY (\`added_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_c143cbc0299e1f9220c4b5debd8\` FOREIGN KEY (\`supplierId\`) REFERENCES \`supplier\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_dcf7550e6f03fb1414ed41628f0\` FOREIGN KEY (\`inventoryId\`) REFERENCES \`inventory\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_dcf7550e6f03fb1414ed41628f0\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_c143cbc0299e1f9220c4b5debd8\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_103cec6966ad062a779ec25536e\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_0633fb8c8bf00bb25890f4b2ae2\``);
        await queryRunner.query(`ALTER TABLE \`inventory\` DROP FOREIGN KEY \`FK_c8622e1e24c6d054d36e8824490\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP FOREIGN KEY \`FK_29cfdad4178e68164711ae51bd7\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP FOREIGN KEY \`FK_63cca4adcd28b6fe19bc4ceb22f\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_2fa435da96296948770716303d5\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_f6a89a945c446c9fdae718d1709\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_fd5199dbe0a822181eb05795e6e\``);
        await queryRunner.query(`ALTER TABLE \`sells\` DROP FOREIGN KEY \`FK_98783c65c664df6dd903b561d5f\``);
        await queryRunner.query(`ALTER TABLE \`sells\` DROP FOREIGN KEY \`FK_076b4238cf89d6b602e7a75d101\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`detail_order\` DROP FOREIGN KEY \`FK_4c3eb3ee75d81ef599c73aa396b\``);
        await queryRunner.query(`ALTER TABLE \`detail_order\` DROP FOREIGN KEY \`FK_28c643f280d3f04dd8d53c4b906\``);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` DROP FOREIGN KEY \`FK_5e8a95d64e5b56059fefa78e85e\``);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` DROP FOREIGN KEY \`FK_236a83d394e727d0b8e2a004efb\``);
        await queryRunner.query(`DROP INDEX \`REL_dcf7550e6f03fb1414ed41628f\` ON \`products\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`supplierId\` \`supplierId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`added_by\` \`added_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`id_category\` \`id_category\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_c143cbc0299e1f9220c4b5debd8\` FOREIGN KEY (\`supplierId\`) REFERENCES \`supplier\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_103cec6966ad062a779ec25536e\` FOREIGN KEY (\`added_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_0633fb8c8bf00bb25890f4b2ae2\` FOREIGN KEY (\`id_category\`) REFERENCES \`categories\`(\`idCategory\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD CONSTRAINT \`FK_63cca4adcd28b6fe19bc4ceb22f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`productId\` \`productId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`id_client\` \`id_client\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`id_user\` \`id_user\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`endDate\` \`endDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`clientName\` \`clientName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`sellDate\` \`sellDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_2fa435da96296948770716303d5\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_f6a89a945c446c9fdae718d1709\` FOREIGN KEY (\`id_client\`) REFERENCES \`clients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_fd5199dbe0a822181eb05795e6e\` FOREIGN KEY (\`id_user\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`id_client\` \`id_client\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`id_user\` \`id_user\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`clientName\` \`clientName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`sellDate\` \`sellDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`sells\` ADD CONSTRAINT \`FK_98783c65c664df6dd903b561d5f\` FOREIGN KEY (\`id_client\`) REFERENCES \`clients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sells\` ADD CONSTRAINT \`FK_076b4238cf89d6b602e7a75d101\` FOREIGN KEY (\`id_user\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` CHANGE \`productId\` \`productId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` CHANGE \`orderId\` \`orderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` ADD CONSTRAINT \`FK_4c3eb3ee75d81ef599c73aa396b\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` ADD CONSTRAINT \`FK_28c643f280d3f04dd8d53c4b906\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`notes\` \`notes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`city\` \`city\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`contactPhone\` \`contactPhone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`clients\` CHANGE \`phone\` \`phone\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`clients\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` CHANGE \`id_sell\` \`id_sell\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` CHANGE \`id_product\` \`id_product\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` ADD CONSTRAINT \`FK_5e8a95d64e5b56059fefa78e85e\` FOREIGN KEY (\`id_sell\`) REFERENCES \`sells\`(\`idSell\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` ADD CONSTRAINT \`FK_236a83d394e727d0b8e2a004efb\` FOREIGN KEY (\`id_product\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP INDEX \`IDX_dcf7550e6f03fb1414ed41628f\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`inventoryId\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP COLUMN \`inventoryId\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD \`product_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD \`quantity\` int NOT NULL`);
        await queryRunner.query(`DROP INDEX \`REL_c8622e1e24c6d054d36e882449\` ON \`inventory\``);
        await queryRunner.query(`DROP TABLE \`inventory\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD CONSTRAINT \`FK_5c3bec1682252c36fa161587738\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
