import { MigrationInterface, QueryRunner } from "typeorm";

export class AddedRentalAndRentalDetailEntity1738597780116 implements MigrationInterface {
    name = 'AddedRentalAndRentalDetailEntity1738597780116'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_2fa435da96296948770716303d5\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_f6a89a945c446c9fdae718d1709\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_fd5199dbe0a822181eb05795e6e\``);
        await queryRunner.query(`CREATE TABLE \`rental_detail\` (\`id\` int NOT NULL AUTO_INCREMENT, \`quantity\` int NOT NULL, \`unitPrice\` decimal(10,2) NOT NULL, \`subtotal\` decimal(10,2) NOT NULL, \`rentalId\` int NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`idSell\` \`idSell\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`idSell\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`sellDate\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`totalPrice\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`clientName\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`id_user\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`id_client\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`productId\``);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`total\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`startDate\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`clientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` DROP FOREIGN KEY \`FK_236a83d394e727d0b8e2a004efb\``);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` DROP FOREIGN KEY \`FK_5e8a95d64e5b56059fefa78e85e\``);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` CHANGE \`id_product\` \`id_product\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` CHANGE \`id_sell\` \`id_sell\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`contactPhone\` \`contactPhone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`city\` \`city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`notes\` \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` DROP FOREIGN KEY \`FK_28c643f280d3f04dd8d53c4b906\``);
        await queryRunner.query(`ALTER TABLE \`detail_order\` DROP FOREIGN KEY \`FK_4c3eb3ee75d81ef599c73aa396b\``);
        await queryRunner.query(`ALTER TABLE \`detail_order\` CHANGE \`orderId\` \`orderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` CHANGE \`productId\` \`productId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`endDate\``);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`endDate\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_0633fb8c8bf00bb25890f4b2ae2\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_103cec6966ad062a779ec25536e\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_c143cbc0299e1f9220c4b5debd8\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_dcf7550e6f03fb1414ed41628f0\``);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`id_category\` \`id_category\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`added_by\` \`added_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`supplierId\` \`supplierId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`inventoryId\` \`inventoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory\` DROP FOREIGN KEY \`FK_c8622e1e24c6d054d36e8824490\``);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`productId\` \`productId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP FOREIGN KEY \`FK_63cca4adcd28b6fe19bc4ceb22f\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP FOREIGN KEY \`FK_29cfdad4178e68164711ae51bd7\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`inventoryId\` \`inventoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sells\` DROP FOREIGN KEY \`FK_076b4238cf89d6b602e7a75d101\``);
        await queryRunner.query(`ALTER TABLE \`sells\` DROP FOREIGN KEY \`FK_98783c65c664df6dd903b561d5f\``);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`sellDate\` \`sellDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`clientName\` \`clientName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`id_user\` \`id_user\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`id_client\` \`id_client\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`clients\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`clients\` CHANGE \`phone\` \`phone\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` ADD CONSTRAINT \`FK_236a83d394e727d0b8e2a004efb\` FOREIGN KEY (\`id_product\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` ADD CONSTRAINT \`FK_5e8a95d64e5b56059fefa78e85e\` FOREIGN KEY (\`id_sell\`) REFERENCES \`sells\`(\`idSell\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` ADD CONSTRAINT \`FK_28c643f280d3f04dd8d53c4b906\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` ADD CONSTRAINT \`FK_4c3eb3ee75d81ef599c73aa396b\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_62d4035ac69898bddd95d399c77\` FOREIGN KEY (\`clientId\`) REFERENCES \`clients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental_detail\` ADD CONSTRAINT \`FK_dd490f911c7263cb3eb6de20a0f\` FOREIGN KEY (\`rentalId\`) REFERENCES \`rental\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental_detail\` ADD CONSTRAINT \`FK_22f6a661b6106764479930a82b4\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_0633fb8c8bf00bb25890f4b2ae2\` FOREIGN KEY (\`id_category\`) REFERENCES \`categories\`(\`idCategory\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_103cec6966ad062a779ec25536e\` FOREIGN KEY (\`added_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_c143cbc0299e1f9220c4b5debd8\` FOREIGN KEY (\`supplierId\`) REFERENCES \`supplier\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_dcf7550e6f03fb1414ed41628f0\` FOREIGN KEY (\`inventoryId\`) REFERENCES \`inventory\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory\` ADD CONSTRAINT \`FK_c8622e1e24c6d054d36e8824490\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD CONSTRAINT \`FK_63cca4adcd28b6fe19bc4ceb22f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD CONSTRAINT \`FK_29cfdad4178e68164711ae51bd7\` FOREIGN KEY (\`inventoryId\`) REFERENCES \`inventory\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sells\` ADD CONSTRAINT \`FK_076b4238cf89d6b602e7a75d101\` FOREIGN KEY (\`id_user\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sells\` ADD CONSTRAINT \`FK_98783c65c664df6dd903b561d5f\` FOREIGN KEY (\`id_client\`) REFERENCES \`clients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`sells\` DROP FOREIGN KEY \`FK_98783c65c664df6dd903b561d5f\``);
        await queryRunner.query(`ALTER TABLE \`sells\` DROP FOREIGN KEY \`FK_076b4238cf89d6b602e7a75d101\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP FOREIGN KEY \`FK_29cfdad4178e68164711ae51bd7\``);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` DROP FOREIGN KEY \`FK_63cca4adcd28b6fe19bc4ceb22f\``);
        await queryRunner.query(`ALTER TABLE \`inventory\` DROP FOREIGN KEY \`FK_c8622e1e24c6d054d36e8824490\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_dcf7550e6f03fb1414ed41628f0\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_c143cbc0299e1f9220c4b5debd8\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_103cec6966ad062a779ec25536e\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_0633fb8c8bf00bb25890f4b2ae2\``);
        await queryRunner.query(`ALTER TABLE \`rental_detail\` DROP FOREIGN KEY \`FK_22f6a661b6106764479930a82b4\``);
        await queryRunner.query(`ALTER TABLE \`rental_detail\` DROP FOREIGN KEY \`FK_dd490f911c7263cb3eb6de20a0f\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_62d4035ac69898bddd95d399c77\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`detail_order\` DROP FOREIGN KEY \`FK_4c3eb3ee75d81ef599c73aa396b\``);
        await queryRunner.query(`ALTER TABLE \`detail_order\` DROP FOREIGN KEY \`FK_28c643f280d3f04dd8d53c4b906\``);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` DROP FOREIGN KEY \`FK_5e8a95d64e5b56059fefa78e85e\``);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` DROP FOREIGN KEY \`FK_236a83d394e727d0b8e2a004efb\``);
        await queryRunner.query(`ALTER TABLE \`clients\` CHANGE \`phone\` \`phone\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`clients\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`id_client\` \`id_client\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`id_user\` \`id_user\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`clientName\` \`clientName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sells\` CHANGE \`sellDate\` \`sellDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`sells\` ADD CONSTRAINT \`FK_98783c65c664df6dd903b561d5f\` FOREIGN KEY (\`id_client\`) REFERENCES \`clients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sells\` ADD CONSTRAINT \`FK_076b4238cf89d6b602e7a75d101\` FOREIGN KEY (\`id_user\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`inventoryId\` \`inventoryId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD CONSTRAINT \`FK_29cfdad4178e68164711ae51bd7\` FOREIGN KEY (\`inventoryId\`) REFERENCES \`inventory\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` ADD CONSTRAINT \`FK_63cca4adcd28b6fe19bc4ceb22f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`productId\` \`productId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory\` ADD CONSTRAINT \`FK_c8622e1e24c6d054d36e8824490\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`inventoryId\` \`inventoryId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`supplierId\` \`supplierId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`added_by\` \`added_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`id_category\` \`id_category\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_dcf7550e6f03fb1414ed41628f0\` FOREIGN KEY (\`inventoryId\`) REFERENCES \`inventory\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_c143cbc0299e1f9220c4b5debd8\` FOREIGN KEY (\`supplierId\`) REFERENCES \`supplier\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_103cec6966ad062a779ec25536e\` FOREIGN KEY (\`added_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_0633fb8c8bf00bb25890f4b2ae2\` FOREIGN KEY (\`id_category\`) REFERENCES \`categories\`(\`idCategory\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`endDate\``);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`endDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` CHANGE \`productId\` \`productId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` CHANGE \`orderId\` \`orderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` ADD CONSTRAINT \`FK_4c3eb3ee75d81ef599c73aa396b\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`detail_order\` ADD CONSTRAINT \`FK_28c643f280d3f04dd8d53c4b906\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`notes\` \`notes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`city\` \`city\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`supplier\` CHANGE \`contactPhone\` \`contactPhone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` CHANGE \`id_sell\` \`id_sell\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` CHANGE \`id_product\` \`id_product\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` ADD CONSTRAINT \`FK_5e8a95d64e5b56059fefa78e85e\` FOREIGN KEY (\`id_sell\`) REFERENCES \`sells\`(\`idSell\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sell_detail\` ADD CONSTRAINT \`FK_236a83d394e727d0b8e2a004efb\` FOREIGN KEY (\`id_product\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`clientId\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`startDate\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`total\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`productId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`id_client\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`id_user\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`clientName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`totalPrice\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`sellDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`idSell\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD PRIMARY KEY (\`idSell\`)`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`idSell\` \`idSell\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`DROP TABLE \`rental_detail\``);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_fd5199dbe0a822181eb05795e6e\` FOREIGN KEY (\`id_user\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_f6a89a945c446c9fdae718d1709\` FOREIGN KEY (\`id_client\`) REFERENCES \`clients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_2fa435da96296948770716303d5\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
